### ISSUE TITLE
Problems in Orthogonal Projection

### ISSUE THREAD

**Issue by FarawayRay** [CedricGuillemet/LibGizmo#7]
When orthogonal has some problems
Unrecognizable axis

**Comment by FarawayRay** [comment]
Currently the drawing is tied directly to the input projection matrix. If you input an orthographic projection then often the widget drawing is tiny. the mouse can't find widget  lines

**Comment by FarawayRay** [comment]
i got it, it's my mistake, we should do some filters for ortho
i find a bug:
1. press 3 into scale and add x value(bigger)
2. press 2 into rotation and rotate around z, the model will be deformation

no scale value change is true, but scale changed ,  the model is abnormal

**Comment by CedricGuillemet** [comment]
Libgizmo is not really maintained. Please check Imguizmo. At least, the math behind it is better than in libgizmo.

**Comment by FarawayRay** [comment]
thank u reply
this lib is easy to integrate and Instead of relying on other frameworks（IMGUI）,so I prefer to maintain this lib.
i will see Imguizmo about this problem

**Comment by FarawayRay** [comment]
i get the method to solve model abnormal
the m_OrigScale is scaling matrix, so this is current matrix
It turns out that this is the identity matrix that causes this problem
thanks for the gizmo
